services:
  ml:
    build: ./Machine_Learning/Traning
    ports:
      - "8001:8001"

  backend:
    build: ./Spring_Backend/fraudDetect
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mysql:
    image: mysql:8.3
    container_name: pict_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frauddb
      MYSQL_USER: fraud
      MYSQL_PASSWORD: fraud
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -u fraud -pfraud -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
