version: "3.9"

services:
  ml:
    build: ./Machine_Learning/Traning
    ports:
      - "8001:8001"

  backend:
    build: ./Spring_Backend/fraudDetect
    ports:
      - "8080:8080"
    depends_on:
      - ml

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
